CREATE TABLE pilote(
   PLNUM INT,
   PLNOM VARCHAR(50),
   PLPRENOM VARCHAR(50),
   VILLE VARCHAR(50),
   SALAIRE float,
   PRIMARY KEY(PLNUM)
);

CREATE TABLE avion(
   AVNUM INT,
   AVNOM VARCHAR(50),
   CAPACITE INT,
   LOCALISATION VARCHAR(50),
   PRIMARY KEY(AVNUM)
);

CREATE TABLE vol(
   VOLNUM INT,
   VILLEDEP VARCHAR(50),
   VILLEARR VARCHAR(50),
   HEUREDEP TIME,
   HEUREARR TIME,
   PLNUM INT NOT NULL,
   AVNUM INT NOT NULL,
   PRIMARY KEY(VOLNUM),
   FOREIGN KEY(PLNUM) REFERENCES pilote(PLNUM),
   FOREIGN KEY(AVNUM) REFERENCES avion(AVNUM)
);
